name:                HaskTorrent
version:             0.1.0.0
github:              "githubuser/HaskTorrent"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/HaskTorrent#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- time
- servant-server
- servant-multipart
- uri-encode
- cryptonite
- memory
- wai
- wai-cors
- http-media
- wai-extra
- warp
- persistent
- persistent-template
- bencode
- bson
- mongoDB
- text
- network
- bytestring
- containers
- unordered-containers

library:
  source-dirs: src

executables:
  HaskTorrent-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - HaskTorrent

tests:
  HaskTorrent-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - HaskTorrent
    - hspec
    - hspec-wai
    - hspec-wai-json
    - aeson
